apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devsecops
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: supersecretpassword
  POSTGRES_DB: tasksdb
  POSTGRES_INITDB_ARGS: "--encoding=UTF8"
